### ISSUE TITLE
Add support for `less-plugin-clean-css`

### ISSUE THREAD

**Issue by styfle** [zeit/node-file-trace#43]
Package: https://www.npmjs.com/package/less-plugin-clean-css

The following integration test fails:

```js
const LessPluginCleanCSS = require('less-plugin-clean-css');
console.log('The less plugin clean css is type ' + typeof LessPluginCleanCSS);
```

The error is:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './base64-vlq'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at stringRequire (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-7062704343464894/node_modules/amdefine/amdefine.js:220:28)
    at amdRequire (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-7062704343464894/node_modules/amdefine/amdefine.js:113:24)
    at Object.<anonymous> (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-7062704343464894/node_modules/clean-css/node_modules/source-map/lib/source-map/source-map-generator.js:12:19)
    at runFactory (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-7062704343464894/node_modules/amdefine/amdefine.js:183:30)
    at define (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-7062704343464894/node_modules/amdefine/amdefine.js:277:13)
    at Object.<anonymous> (/private/var/folders/v7/6kzxdgb93x328tk9pg633s200000gn/T/node-file-trace-7062704343464894/node_modules/clean-css/node_modules/source-map/lib/source-map/source-map-generator.js:10:1)
```

Reported here: https://spectrum.chat/zeit/now/error-cannot-find-module-base64-vlq~d61cd796-d48c-4a65-9d5c-045fae23964b

**Comment by styfle** [comment]
Closing since the user upgraded to `clean-css` v4 and it works now.
