### ISSUE TITLE
unable to run on typescript file

### ISSUE THREAD

**Issue by andycmaj** [zeit/node-file-trace#73]
target file: `/Workspace/github/asynchronous-dev/botany/ui/pages/api/auth/[provider].ts`

## file contents:

```
import withPassport, { passport } from 'lib/withPassport';
import { NextApiResponse, NextApiRequest } from 'next';
import debug from 'shared/debug';

const handler = (req: NextApiRequest, res: NextApiResponse) => {
  const { provider } = req.query;
  if (!provider) {
    return { statusCode: 404 };
  }

  debug('auth', 'begin', provider);
  passport.authenticate(provider)(req, res, (...args) => {
    debug('auth', 'next', args);
  });
};

export default withPassport(handler);

```

## trace call

```
yarn run v1.19.0
$ babel-node-ts trace.ts
{ fileList: [ 'pages/api/auth/[provider].ts' ],
  esmFileList: [],
  reasons:
   [Object: null prototype] {
     'pages/api/auth/[provider].ts': { type: 'initial', ignored: false, parents: [] } },
  warnings:
   [ Error: Failed to parse /Workspace/github/asynchronous-dev/botany/ui/pages/api/auth/[provider].ts as module:
     Unexpected token (5:20)
         at module.exports (/Workspace/github/asynchronous-dev/botany/node_modules/@zeit/node-file-trace/src/analyze.js:210:24)
         at Job.emitDependency (/Workspace/github/asynchronous-dev/botany/node_modules/@zeit/node-file-trace/src/node-file-trace.js:206:43)
         at Promise.all.files.map.file (/Workspace/github/asynchronous-dev/botany/node_modules/@zeit/node-file-trace/src/node-file-trace.js:31:18)
         at Array.map (<anonymous>)
         at module.exports (/Workspace/github/asynchronous-dev/botany/node_modules/@zeit/node-file-trace/src/node-file-trace.js:27:27)
         at Object.<anonymous> (/Workspace/github/asynchronous-dev/botany/ui/trace.ts:10:31)
         at Module._compile (internal/modules/cjs/loader.js:776:30)
         at Module._compile (/Workspace/github/asynchronous-dev/botany/node_modules/pirates/lib/index.js:99:24)
         at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
         at Object.newLoader (/Workspace/github/asynchronous-dev/botany/node_modules/pirates/lib/index.js:104:7) ] }
undefined
✨  Done in 2.13s.
```

**Comment by andycmaj** [comment]
looks like it's not parsing my entrypoint as typescript even though i'm using `ts:true`

## trace script

```
import trace from '@zeit/node-file-trace';
require('ts-node/register');

// const trace = require('@zeit/node-file-trace');
trace(['./pages/api/auth/[provider].ts'], {
  ts: true,
  base: process.cwd(),
  log: true,
})
  .then(o => console.log(o))
  .then(e => console.error(e));
```

**Comment by andycmaj** [comment]
note that tracing is responsible for now.sh build hangs when using api handlers: https://spectrum.chat/zeit/now/now-sh-builds-hang-at-preparing-serverless-function-files~28197a5d-ef8d-49a9-9a04-c9f91b74b584

**Comment by styfle** [comment]
This is expected behavior because you need to provide a `readFile()` callback that compiles typescript to javascript in order for `node-file-trace` to understand how to parse the file.

See the `@now/node` Builder for an example https://github.com/zeit/now/blob/16ef6229e4ff0fca6817334f409338d640756f2e/packages/now-node/src/index.ts#L171

**Comment by andycmaj** [comment]
hmm might wanna document that :)

![ScreenCapture at Sun Oct 13 18:22:33 PDT 2019](https://user-images.githubusercontent.com/97470/66725395-76a07900-ede6-11e9-8ee1-e9f1603d539d.png)
