### ISSUE TITLE
hummus-recipe is failing

### ISSUE THREAD

**Issue by paulogdm** [zeit/node-file-trace#89]
**Reproducible example:** https://codesandbox.io/s/distracted-bardeen-kks92
**Public deployment with logs:** https://zeit.co/pgdm/csb-kks92/qo1379ftg

```
ERROR	TypeError: this._getEncryptOptions is not a function
    at new Recipe (/var/task/node_modules/hummus-recipe/lib/Recipe.js:31:36)
    at /var/task/api/index.js:6:18
    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/task/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/task/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
    at /var/task/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/task/node_modules/express/lib/router/index.js:335:12)
    at next (/var/task/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/var/task/node_modules/express/lib/middleware/init.js:40:5)
```

**Comment by ssijak** [comment]
Hey did you manage to fix this?
